const ZONES = {
  algemeen: {
    id: 'algemeen',
    label: 'Algemeen overzicht',
    color: '#888888',
    showPin: false,
    description: 'Totaaloverzicht van de toekomstige mechanische werkplaats. Vijf werkzones, zichtbare looplijnen en veiligheidsafbakening.',
    safety: [
      'Volg de gemarkeerde looplijnen — geen kortere wegen door werkzones',
      'Draag steeds correcte PBM: veiligheidsbril, schoenen S3, gehoorbescherming waar nodig',
      'Respecteer LOTO/LOTOTO-procedures bij elke onderbreking',
      'Brandblussers op vaste locaties — niet verplaatsen',
    ],
  },
  blauw: {
    id: 'blauw',
    label: 'Blauw verspaning',
    color: '#3B82F6',
    showPin: true,
    description: 'Klassieke verspaningstechnieken: frezen, draaien, slijpen en boren. Magneetveld voor opspanning en meetbank voor controle.',
  },
  groen: {
    id: 'groen',
    label: 'Groen Montage',
    color: '#22C55E',
    showPin: true,
    description: 'Vier montagetafels met lades voor handgereedschap. Focus op precieze assemblage, demontage en kwaliteitscontrole.',
  },
  rood: {
    id: 'rood',
    label: 'Rood Lassen',
    color: '#EF4444',
    showPin: true,
    description: 'Lasafdeling met lasrobot, afgescheiden door brand- en lasgordijnen. Strikte regels rond ventilatie en PBM.',
  },
  geel: {
    id: 'geel',
    label: 'Geel CNC',
    color: '#F5C518',
    showPin: true,
    description: 'CNC-zone met freesbank en draaibank. Werken volgens programma — controle van nulpunt en gereedschapscorrectie verplicht.',
  },
  oranje: {
    id: 'oranje',
    label: 'Oranje Magazijn',
    color: '#F97316',
    showPin: true,
    description: 'Links de gereedschaps­rekken, rechts een metaalrek met pc-post om onderdelen op te zoeken in het beheersysteem.',
  },
};

const ZONE_ORDER = ['algemeen', 'blauw', 'groen', 'rood', 'geel', 'oranje'];
const MACHINES = [
  {
    id: 'slijp-boren',
    name: 'slijpmachine voor boren',
    zone: 'blauw',
    description: 'Speciale slijpmachine voor het bijslijpen van spiraal- en centerboren. Zorgt voor scherpe boorpunt met juiste tophoek (118°).',
    veiligheid: {
      pbm: ['Veiligheidsbril (verplicht)', 'Stofmasker FFP2', 'Gehoorbescherming aanbevolen'],
      regels: [
        'Nooit slijpen zonder beschermkap',
        'Werkstuk vast in opspanning — nooit met de hand vasthouden',
        'Slijpschijf controleren op barsten vóór gebruik (klanktest)',
        'Maximaal toerental op de schijf nooit overschrijden',
      ],
    },
    handleiding: {
      stappen: [
        'Hoofdschakelaar aan en wacht tot het toerental stabiel is',
        'Boor in de opspanning plaatsen, hoek op 59° (= halve tophoek)',
        'Boorpunt licht tegen schijf brengen, met koeling',
        'Beide snijkanten gelijk slijpen — anders wijkt de boor af',
        'Controleer met boormal of de hoek correct is',
      ],
    },
    controle: ['Wekelijks: slijpschijf op slijtage', 'Maandelijks: opspanning recht zetten', 'Halfjaarlijks: lagers controleren'],
    smering: ['Lagers: vetnippel — 2x per jaar (KP2K-30)', 'Opspanningsdraad: dunne olie (ISO VG 32) — wekelijks 1 druppel'],
  },
  {
    id: 'slijp-frezen',
    name: 'slijpmachine voor frezen',
    zone: 'blauw',
    description: 'Universele slijpmachine voor het opnieuw aanzetten van frezen, beitels en speciale gereedschappen. Voorzien van precisie-opspanning.',
    veiligheid: {
      pbm: ['Veiligheidsbril', 'Lederen handschoenen NIET gebruiken bij draaiende schijf', 'Stofafzuiging aan'],
      regels: [
        'Schijven controleren op haarscheuren',
        'Werkstuk koel houden — gloeien = uitharden vernield',
        'Vonken niet richting brandbaar materiaal',
      ],
    },
    handleiding: {
      stappen: [
        'Selecteer de juiste opspanning voor het type frees',
        'Stel de slijphoek in volgens fresentekening',
        'Slijpschijf in koelvloeistof brengen voor stationair toerental',
        'Lichte aandrukkracht — meerdere passes',
      ],
    },
    controle: ['Wekelijks: koelmiddelniveau', 'Maandelijks: opspanrondheid meten met meetklok'],
    smering: ['Hoofdspil: olie ISO VG 46 — controle elke 200 bedrijfsuren', 'Geleidingen: lineair vet — wekelijks'],
  },
  {
    id: 'frees-1',
    name: 'Freesmachine 1',
    zone: 'blauw',
    description: 'Conventionele kolomfreesmachine voor opleidingsdoeleinden. Geschikt voor vlakfrezen, sleuven en eenvoudige contouren.',
    veiligheid: {
      pbm: ['Veiligheidsbril', 'Veiligheidsschoenen S3', 'Geen losse kledij, lange haren vast'],
      regels: [
        'Spaanafzuiging steeds aan',
        'Nooit met de hand spanen verwijderen — gebruik haak',
        'Werkstuk volledig opspannen vóór bewerking',
        'Toerental afstemmen op materiaal en freesdiameter',
      ],
    },
    handleiding: {
      stappen: [
        'Hoofdschakelaar aan, smering activeren',
        'Frees opspannen, uitlijning controleren',
        'Werkstuk centreren en stevig vastzetten',
        'Nulpunt instellen via kantentaster',
        'Toerental en voeding selecteren volgens snijdiagram',
        'Eerste passage minimaal — voel en hoor de machine',
      ],
    },
    controle: ['Dagelijks: oliepeil hoofdspil', 'Wekelijks: koelvloeistof reinigen', 'Maandelijks: aanslagen herkalibreren'],
    smering: ['Hoofdspil: ISO VG 32 — peilen vóór elke shift', 'X/Y/Z-geleidingen: automatische smering — vetreservoir maandelijks bijvullen', 'Spilkop: vet KP2K — halfjaarlijks'],
  },
  {
    id: 'frees-2',
    name: 'Freesmachine 2',
    zone: 'blauw',
    description: 'Identiek aan Freesmachine 1, opgesteld als parallelpost voor klasoefeningen.',
    veiligheid: {
      pbm: ['Veiligheidsbril', 'Veiligheidsschoenen S3'],
      regels: ['Zie Freesmachine 1', 'Per machine 1 student aan de bediening'],
    },
    handleiding: { stappen: ['Identiek aan Freesmachine 1 — zie procedure aldaar.'] },
    controle: ['Volg het schema van Freesmachine 1'],
    smering: ['Volg het schema van Freesmachine 1'],
  },
  {
    id: 'frees-3',
    name: 'Freesmachine 3',
    zone: 'blauw',
    description: 'Conventionele kolomfreesmachine, opstelling identiek aan posten 1 & 2.',
    veiligheid: { pbm: ['Veiligheidsbril', 'Veiligheidsschoenen S3'], regels: ['Zie Freesmachine 1'] },
    handleiding: { stappen: ['Volg de standaardprocedure voor freesmachines.'] },
    controle: ['Volg het standaardschema'],
    smering: ['Volg het standaardschema'],
  },
  {
    id: 'frees-4',
    name: 'Freesmachine 4',
    zone: 'blauw',
    description: 'Conventionele kolomfreesmachine, vierde en laatste post in de verspaningsrij.',
    veiligheid: { pbm: ['Veiligheidsbril', 'Veiligheidsschoenen S3'], regels: ['Zie Freesmachine 1'] },
    handleiding: { stappen: ['Volg de standaardprocedure voor freesmachines.'] },
    controle: ['Volg het standaardschema'],
    smering: ['Volg het standaardschema'],
  },
  {
    id: 'radiaalboor',
    name: 'Radiaalboor',
    zone: 'blauw',
    description: 'Radiaalboormachine voor grote werkstukken. Verstelbare arm zodat het werkstuk niet hoeft te bewegen — alleen de boorkop.',
    veiligheid: {
      pbm: ['Veiligheidsbril', 'Schoenen S3', 'Geen handschoenen bij draaiende spil'],
      regels: [
        'Werkstuk vastklemmen — NOOIT met de hand vasthouden',
        'Boor opspannen tot aanslag',
        'Vóór starten: arm vergrendelen',
      ],
    },
    handleiding: { stappen: [
      'Arm en kolom positioneren boven het boorpunt',
      'Beide vergrendelingen aandraaien',
      'Toerental kiezen volgens boor­diameter en materiaal',
      'Met de hand voeden — voel weerstand',
    ] },
    controle: ['Dagelijks: vergrendeling arm/kolom', 'Maandelijks: spie­spel meten'],
    smering: ['Arm: vet — 1x per maand', 'Spilkop: olie ISO VG 32 — peilen wekelijks'],
  },
  {
    id: 'draaibank-1',
    name: 'Draaibank Harrison',
    zone: 'blauw',
    description: 'Conventionele draaibank voor cilindrisch, conisch en schroefdraaddraaien. Werkpaard van de verspaningszone.',
    veiligheid: {
      pbm: ['Veiligheidsbril', 'Geen handschoenen', 'Spaanscherm naar beneden'],
      regels: [
        'Spankop met spansleutel — sleutel ALTIJD uitnemen vóór starten',
        'Werkstuk uitsteek max. 3× diameter zonder steunpop',
        'Spanen verwijderen met haak, machine uit',
      ],
    },
    handleiding: { stappen: [
      'Werkstuk in spankop, uitlijning meten',
      'Beitel opspannen op centerhoogte',
      'Toerental kiezen — Vc = (π × d × n) / 1000',
      'Voeding instellen, koelmiddel aan',
      'Eerste snede licht — controleer maatvoering',
    ] },
    controle: ['Dagelijks: oliepeil leibanen', 'Wekelijks: spankop reinigen', 'Maandelijks: hartlijn uitlijnen'],
    smering: ['Spilkop: ISO VG 68 — peilen vóór elke shift', 'Leibanen: automatisch — reservoir maandelijks', 'Loopspil: vet KP2K — halfjaarlijks'],
  },
  {
    id: 'slijpmachine',
    name: 'Slijpmachine',
    zone: 'blauw',
    description: 'Universele tafelslijpmachine voor het scherpen en bijwerken van handgereedschap.',
    veiligheid: {
      pbm: ['Veiligheidsbril (verplicht)', 'Stofmasker FFP2'],
      regels: ['Beschermkap controleren', 'Schijf-tot-steun max. 3 mm', 'Werkstuk koelen — niet laten blauwkleuren'],
    },
    handleiding: { stappen: ['Schijf op snelheid laten komen', 'Lichte druk, werkstuk bewegen', 'Regelmatig dompelen in koelwater'] },
    controle: ['Maandelijks: schijven richten', 'Halfjaarlijks: schijfwissel'],
    smering: ['Lagers: gesloten — geen onderhoud', 'Steunarm: dunne olie wekelijks'],
  },

  {
    id: 'montagetafel-1',
    name: 'Montagetafel 1',
    zone: 'groen',
    description: 'Werkbank met lades voor handgereedschap, schroefverbindingen en kleine montagewerken. Antistatische mat aanwezig.',
    veiligheid: {
      pbm: ['Veiligheidsbril bij hamertaken', 'ESD-polsband bij elektronica'],
      regels: ['5S aan het einde van elke shift', 'Gereedschap op shadow-board terug', 'Geen vetten of olie op de werkmat'],
    },
    handleiding: { stappen: ['Werkstuk vastzetten in bankschroef', 'Gebruik momentsleutel voor kritieke verbindingen', 'Markeer afgewerkte stappen op de werkfiche'] },
    controle: ['Wekelijks: bankschroef-kaken op slijtage', 'Maandelijks: momentsleutel kalibreren'],
    smering: ['Bankschroef: dunne olie maandelijks', 'Lades-glijders: silicone-spray halfjaarlijks'],
  },
  {
    id: 'montagetafel-2',
    name: 'Montagetafel 2',
    zone: 'groen',
    description: 'Identiek aan Montagetafel 1.',
    veiligheid: { pbm: ['Zie Montagetafel 1'], regels: ['Zie Montagetafel 1'] },
    handleiding: { stappen: ['Zie Montagetafel 1'] },
    controle: ['Zie Montagetafel 1'],
    smering: ['Zie Montagetafel 1'],
  },
  {
    id: 'montagetafel-3',
    name: 'Montagetafel 3',
    zone: 'groen',
    description: 'Identiek aan Montagetafel 1.',
    veiligheid: { pbm: ['Zie Montagetafel 1'], regels: ['Zie Montagetafel 1'] },
    handleiding: { stappen: ['Zie Montagetafel 1'] },
    controle: ['Zie Montagetafel 1'],
    smering: ['Zie Montagetafel 1'],
  },
  {
    id: 'montagetafel-4',
    name: 'Montagetafel 4',
    zone: 'groen',
    description: 'Identiek aan Montagetafel 1.',
    veiligheid: { pbm: ['Zie Montagetafel 1'], regels: ['Zie Montagetafel 1'] },
    handleiding: { stappen: ['Zie Montagetafel 1'] },
    controle: ['Zie Montagetafel 1'],
    smering: ['Zie Montagetafel 1'],
  },
  {
    id: 'meetbank',
    name: 'Meetbank',
    zone: 'groen',
    description: 'Tafel met meetbank en digitaal bord. Voor kwaliteitscontrole van werkstukken na verspaning of montage.',
    veiligheid: {
      pbm: ['Geen specifieke PBM — handen schoon en droog'],
      regels: ['Geen drinken op de meetbank', 'Meetinstrumenten in foudraal terug', 'Granieten tafel niet beschadigen'],
    },
    handleiding: { stappen: [
      'Werkstuk reinigen van bramen en koelvloeistof',
      'Werkstuk op temperatuur laten komen (20°C)',
      'Meetinstrument kalibreren met blokje',
      'Meting registreren op digitaal bord',
    ] },
    controle: ['Maandelijks: meetinstrumenten herkalibreren', 'Halfjaarlijks: granieten plaat egaliseren'],
    smering: ['Geen smering — alle instrumenten droog houden'],
  },

  {
    id: 'lasrobot',
    name: 'Lasrobot',
    zone: 'rood',
    description: 'Robotgestuurde lasinstallatie voor MIG/MAG. Programmeerbaar voor herhaalbare productiestukken — ideaal voor demonstraties.',
    veiligheid: {
      pbm: ['Auto-darkening lashelm', 'Lasjas leder', 'Veiligheidsschoenen', 'Niet kijken naar de boog — straling!'],
      regels: [
        'Lasgordijnen ALTIJD dicht',
        'Afzuiging maximaal',
        'Niemand binnen de robotcel tijdens beweging',
        'Noodstop binnen handbereik',
      ],
    },
    handleiding: { stappen: [
      'Inlogprocedure op robot-controller',
      'Programma selecteren of teach-in uitvoeren',
      'Gas en draadaanvoer controleren',
      'Eerste cycle in single-step modus',
      'Continue cycle pas na visuele controle',
    ] },
    controle: ['Dagelijks: contactbuis en gasmondstuk', 'Wekelijks: draaddoorvoer reinigen', 'Maandelijks: robotgeleidingen kalibreren'],
    smering: ['Robotgewrichten: smeerprogramma volgens fabrikant — 6 maandelijks', 'Draadtoevoer: niet smeren — droog houden'],
  },
  {
    id: 'lastafel',
    name: 'Lastafel',
    zone: 'rood',
    description: 'Stalen lastafel met opspanopeningen en aardklem. Voor TIG/MIG/elektrode-lassen onder begeleiding.',
    veiligheid: {
      pbm: ['Lashelm', 'Lasjas + handschoenen leder', 'Schoenen S3'],
      regels: ['Lasgordijn dicht', 'Afzuiging direct boven werkstuk', 'Brandblusser binnen 2m', 'Geen brandbaar in zone'],
    },
    handleiding: { stappen: [
      'Werkstuk reinigen en opspannen',
      'Aardklem direct op werkstuk',
      'Parameters kiezen volgens materiaal en dikte',
      'Eerst hechtlassen, dan doorlassen',
    ] },
    controle: ['Wekelijks: aardklem op corrosie', 'Maandelijks: tafelpoten en wielen'],
    smering: ['Spanmiddelen: lichte olie — wekelijks', 'Wielen: vet — halfjaarlijks'],
  },

  {
    id: 'cnc-frees',
    name: 'CNC Freesbank',
    zone: 'geel',
    description: 'Computer-gestuurde freesbank (3-assig) voor precieze productie volgens G-code. Toolwissel via automatische tafel.',
    veiligheid: {
      pbm: ['Veiligheidsbril', 'Schoenen S3', 'Gehoorbescherming bij open deur'],
      regels: [
        'Deur ALTIJD dicht tijdens cyclus',
        'Dry-run vóór elke nieuwe job',
        'Nulpunt controleren met kantentaster',
        'Spanen pas verwijderen na "cycle stop"',
      ],
    },
    handleiding: { stappen: [
      'Werkstuk vastspannen in machineklem',
      'Gereedschappen in revolver — lengtes meten',
      'G-code laden, simulatie draaien',
      'Werknulpunt instellen (G54)',
      'Single-block test, dan automatische cyclus',
    ] },
    controle: ['Dagelijks: koelmiddelconcentratie meten', 'Wekelijks: gereedschapsmaten controleren', 'Maandelijks: lineaire metingen op cirkeltest'],
    smering: ['Hoofdspil: olienevel — automatisch, peilen wekelijks', 'Lineaire geleidingen: centraal vetsmeer­systeem', 'Toolwisselaar: speciaal vet halfjaarlijks'],
  },
  {
    id: 'cnc-draai',
    name: 'CNC Draaibank',
    zone: 'geel',
    description: 'Computer-gestuurde draaibank met live tooling. Voor productie van rotatiesymmetrische onderdelen met hoge precisie.',
    veiligheid: {
      pbm: ['Veiligheidsbril', 'Schoenen S3'],
      regels: ['Bij chuck-test: stevige opspanning verifiëren', 'Spaanafvoer vrij houden', 'Deur dicht tijdens cyclus'],
    },
    handleiding: { stappen: [
      'Materiaal in spankop, uitsteek controleren',
      'Gereedschappen in revolver, offsets meten',
      'Programma simuleren, daarna single block',
      'Eerste werkstuk volledig meten — daarna serie',
    ] },
    controle: ['Dagelijks: koelmiddel en spaanafvoer', 'Wekelijks: spankop reinigen en smeren'],
    smering: ['Spilkop: ISO VG 68 — gesloten systeem', 'Spankop: speciaal spankopvet wekelijks', 'Revolverkop: olienevel automatisch'],
  },

  {
    id: 'rekken-links',
    name: 'Gereedschapsrekken',
    zone: 'oranje',
    description: 'Linker zijde van het magazijn: rekken met handgereedschap, meetinstrumenten en verbruiksartikelen.',
    veiligheid: {
      pbm: ['Schoenen S3'],
      regels: ['Zware items op ooghoogte of lager', 'Ladders correct gebruiken', 'Materiaal niet stapelen boven 1,80m'],
    },
    handleiding: { stappen: ['Uitlening registreren op pc-post', 'Item terug op correcte locatie volgens label', 'Beschadiging direct melden'] },
    controle: ['Maandelijks: stockcontrole vs systeem', 'Halfjaarlijks: rekken op stabiliteit'],
    smering: ['Geen — droog magazijn'],
  },
  {
    id: 'metaalrek',
    name: 'Metaalrek',
    zone: 'oranje',
    description: 'Rechter zijde van het magazijn: metaalrek voor staven, profielen en platen. Geordend per materiaal en afmeting.',
    veiligheid: {
      pbm: ['Schoenen S3', 'Handschoenen bij scherpe kanten', 'Helm bij ophaaltransport'],
      regels: ['Lang materiaal met 2 personen', 'Stalen banden veilig knippen', 'Hijsmiddelen onder de WLL gebruiken'],
    },
    handleiding: { stappen: ['Materiaal opzoeken in pc-systeem', 'Uitname registreren met QR-scan', 'Restmateriaal labelen en teruggeven'] },
    controle: ['Maandelijks: rek-haken op vervorming', 'Halfjaarlijks: belasting-­certificaat'],
    smering: ['Geen — droog houden'],
  },
  {
    id: 'pc-post',
    name: 'PC-post magazijn',
    zone: 'oranje',
    description: 'Computerpost voor het opzoeken van onderdelen, registreren van uitname en raadplegen van technische fiches.',
    veiligheid: { pbm: ['Geen specifieke PBM'], regels: ['Geen drinken bij de pc', 'Steeds afmelden bij vertrek'] },
    handleiding: { stappen: ['Inloggen met studentenaccount', 'Onderdeel opzoeken via zoekbalk of QR-scan', 'Uitname bevestigen', 'Bij retour: scan + locatie verifiëren'] },
    controle: ['Maandelijks: software-updates', 'Halfjaarlijks: scanner kalibreren'],
    smering: ['Niet van toepassing'],
  },
];

const USERS = {
  'dimitri de raeve': { name: 'Dimitri De Raeve', password: 'w8tW00rD', role: 'admin' },
  'niels verellen': { name: 'Niels Verellen', password: 'w8tW00rD', role: 'admin' },
};

window.WERKPLAATS_DATA = { ZONES, ZONE_ORDER, MACHINES, USERS };
